config/routes.rb
Rails.application.routes.draw do

  get 'form_validation/mobile'
  get 'form_validation/email'
  get 'form_validation/username'
  get 'rooms/unauthorized'
  get 'rooms/myroom'
  get 'rooms/confirmed_unconfirmed_bookings'

  devise_for :users
    scope "/admin" do
      resources :users
    end
  resources :amenities
  resources :cities
  resources :roles
  resources :rooms
  resources :images
  resources :bookings
  

  root to: "rooms#index"

end

app/models/amenity.rb
class Amenity < ActiveRecord::Base
	validates_presence_of :name,:description

	belongs_to :user
	
	has_many :amenity_rooms
	has_many :rooms,through: :amenity_rooms
end

app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController
  before_action :authenticate_user!, except:[:index,:show]
  before_action :set_amenity, only: [:show, :edit, :update, :destroy]
  
  load_and_authorize_resource

  # GET /amenities
  # GET /amenities.json
  def index
    @amenities = Amenity.all
  end

  # GET /amenities/1
  # GET /amenities/1.json
  def show
  end

  # GET /amenities/new
  def new
    @amenity = Amenity.new
  end

  # GET /amenities/1/edit
  def edit
  end

  # POST /amenities
  # POST /amenities.json
  def create
    @amenity = Amenity.new(amenity_params)

    respond_to do |format|
      if @amenity.save
        format.html { redirect_to @amenity, notice: 'Amenity was successfully created.' }
        format.json { render :show, status: :created, location: @amenity }
      else
        format.html { render :new }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amenities/1
  # PATCH/PUT /amenities/1.json
  def update
    respond_to do |format|
      if @amenity.update(amenity_params)
        format.html { redirect_to @amenity, notice: 'Amenity was successfully updated.' }
        format.json { render :show, status: :ok, location: @amenity }
      else
        format.html { render :edit }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amenities/1
  # DELETE /amenities/1.json
  def destroy
    @amenity.destroy
    respond_to do |format|
      format.html { redirect_to amenities_url, notice: 'Amenity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amenity
      @amenity = Amenity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amenity_params
      params.require(:amenity).permit(:name, :description)
    end
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/views/amenities/_form.html.erb
<%= form_for(@amenity) do |f| %>
  <% if @amenity.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
          <h2><%= pluralize(@amenity.errors.count, "error") %> prohibited this amenity from being saved:</h2>

          <ul>
          <% @amenity.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
      </div>    
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name,class:'form-control' %>
    <p id = 'nameError'></p>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description ,class:'form-control'%>
    <p id = descriptionError></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  nameHandle = document.getElementById('amenity_name');
  nameErrorHandle = document.getElementById('nameError');
  descriptionHandle = document.getElementById('amenity_description');
  descriptionErrorHandle = document.getElementById('descriptionError');

  nameHandle.onblur = function(){
    if(nameHandle.value.length == 0){
      nameErrorHandle.innerHTML = "Can't be blank";
    } else {
      nameErrorHandle.innerHTML = "";
    }
  }
  
  descriptionHandle.onblur = function(){
    if(descriptionHandle.value.length == 0){
      descriptionErrorHandle.innerHTML = "Can't be blank";
    } else {
      descriptionErrorHandle.innerHTML = "";
    }
  }

</script>

app/views/amenities/edit.html.erb
<div class="panel panel-info">
  <div class="panel-heading">Add New Amenity</div>
    <div class="panel-body">
		<%= render 'form' %>

		<%= link_to 'Show', @amenity %> |
		<%= link_to 'Back', amenities_path %>
	</div>
</div>	

app/views/amenities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Amenities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amenities.each do |amenity| %>
      <tr>
        <td><%= amenity.name %></td>
        <td><%= amenity.description %></td>
        <td><%= link_to 'Show', amenity %></td>
        <% if can? :update,amenity %>
          <td><%= link_to 'Edit', edit_amenity_path(amenity) %></td>
        <% end %>
        <% if can? :destroy,amenity %>
        <td><%= link_to 'Destroy', amenity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create,Amenity.new %>
  <%= link_to 'New Amenity', new_amenity_path %>
<% end %>

app/views/amenities/new.html.erb
<div class="panel panel-info">
  <div class="panel-heading">Add New Amenity</div>
  	<div class="panel-body">
		<%= render 'form' %>
		<%= link_to 'Back', amenities_path %>
	</div>
</div>		

app/views/amenities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @amenity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @amenity.description %>
</p>

<% if can? :update,@amenity %>
	<%= link_to 'Edit', edit_amenity_path(@amenity) %> |
<% end %>
<%= link_to 'Back', amenities_path %>