config/routes.rb
Rails.application.routes.draw do

  get 'form_validation/mobile'
  get 'form_validation/email'
  get 'form_validation/username'
  get 'rooms/unauthorized'
  get 'rooms/myroom'
  get 'rooms/confirmed_unconfirmed_bookings'

  devise_for :users
    scope "/admin" do
      resources :users
    end
  resources :amenities
  resources :cities
  resources :roles
  resources :rooms
  resources :images
  resources :bookings
  

  root to: "rooms#index"

end

app/models/room.rb
class Room < ActiveRecord::Base
	validates_presence_of :name,:description,:rules,:address
	validates_numericality_of :user_id,:city_id,:minimum_days,:latitude,:langitude,:price

	belongs_to :user
	belongs_to :city
	has_many :images
	has_many :bookings
	
	accepts_nested_attributes_for :images

	has_many :amenity_rooms
	has_many :amenities,through: :amenity_rooms

	after_create :set_user_host

	after_create :send_mail_to_admin

	after_update :host_confirmation

	def set_user_host
		host_role = Role.find_by('name=?',"host").id
	    admin_role = Role.find_by('name=?',"admin").id

		if self.user.role_id == admin_role
			self.user.role_id = admin_role
		else
			self.user.role_id = host_role
			self.user.save
		end	
		 
	end

	def role?(role)
      self.user.role.name == role
    end


    #sending mail to admin saying confirm the room
    def send_mail_to_admin
    	Notification.send_mail_to_admin(self).deliver!
    end

    # sending mail to host saying Room has been confirmed

    def host_confirmation
    	#binding.pry
    	SendMailToHost.host_confirmation(self).deliver!
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :authenticate_user!, except:[:index,:show]
	load_and_authorize_resource

  def index
	 @rooms	= Room.all	
  end

  def new	
	@room = Room.new
	@image = Image.new
  end

  def create
	@room = Room.new(room_params)
	 if @room.save
	 	redirect_to rooms_path
	 else
	 	render new_room_path
	 end	
  end

  def show
	@room = Room.find(params[:id])
	@booking = Booking.new
  end

  def edit
	@room = Room.find(params[:id])
  end

def update
	@room = Room.find(params[:id])
		if @room .update_attributes(room_params)
		     redirect_to rooms_path(@room.id)
		else
		    render action: "edit"
	   end
end

def destroy
	@room = Room.find(params[:id])
	@room.destroy
	redirect_to rooms_path
end
def unauthorized
	authorize! :unauthorized,Room.new
	@room = Room.new
	@rooms = Room.where('is_authorized = ?' ,false)	
end
def myroom
	authorize! :myroom,Room.new
	@rooms = Room.all
	@myroom_array = []
	@rooms.each do |room|
		if room.user_id == current_user.id
			@myroom_array << room
		end
	end		
end
def confirmed_unconfirmed_bookings
	authorize! :confirmed_unconfirmed_bookings,Room.new
	@bookings = Booking.all	
	@booking = Booking.new
end

	private
	def room_params
		params[:room].permit(:name,:description,:price,:rules,:minimum_days,:address,:langitude,:latitude,:is_authorized,:city_id,:user_id,amenity_ids: [], images_attributes:[:id,:image,:room_id])
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
	<% if @room .errors.any? %>
	<div class="alert alert-danger">
		<ul>
		<% @room.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>	
	<% end %>
		<div class = "form" %>
			<%= f.label :name %>
			<%= f.text_field :name  %>
		</div>
		<div class = "form" %>
			<%= f.label :description %>
			<%= f.text_area :description %>
		</div>	
		<div class = "form" %>
			<%= f.label :price %>
			<%= f.text_field :price %>
		</div>
		<div class = "form" %>
			<%= f.label :rules %>
			<%= f.text_field :rules %>
		</div>
		<div class="form-group">	
			<%= f.label :minimum_days %>
			<%= f.select :minimum_days ,[1,2,3,4,5],class: "form-control"%>
		</div>	
		<div class="form">
			<%= f.label :address %>
			<%= f.text_area :address  %>
			<p id="addressError"></p>
		</div>	
		<div class="form">
			<%= f.label :latitude %>
			<%= f.text_field :latitude %>
			<p id = "latitudeError"></p>
		</div>	
		<div class="form">
			<%= f.label :langitude %>
			<%= f.text_field :langitude %>
			<p id = "langitudeError"></p> 
		</div>	

			<%# if can? :update,Room.new %>
				<%#= f.label :is_authorized %>
				<%#= f.check_box :is_authorized %>
			<%# end %>	
		<div class="form">
			<% if current_user.role?"admin" %>
				<%= f.label :is_authorized %>
				<%= f.check_box :is_authorized ,:checked => true %>
			<% end %> 
		</div>
		<div class="form">
			<%= f.label :city%>
			<%= f.collection_select :city_id,City.all,:id,:name ,prompt: "Select City"%>
		</div>	
		<div class="form">
			<%= f.label :Amenity %>
		    <%= f.collection_check_boxes :amenity_ids,Amenity.all,:id,:name %> 
		</div>    

		     <%= f.fields_for :images,@image do |ff| %>
		     	<%= ff.label :image %>:
		     	<%= ff.file_field :image %>   	 	
		     <% end %> <br/>

		     <%= f.hidden_field :user_id, value: current_user.id %>
			 <%#= binding.pry %>     
			<%= f.submit %>
		<% end %>
	

<script>
	var addressHandle =  document.getElementById('room_address');
	var addressErrorHandle = document.getElementById('addressError');
	var latitudeHandle = document.getElementById('room_latitude');
	var latitudeErrorHandle = document.getElementById('latitudeError');
	var langitudeHandle = document.getElementById('room_langitude');


	addressHandle.onblur = function(){
		if(addressHandle.value == ""){
			addressErrorHandle.innerHTML = "Can't be blank";
		} else {
			addressErrorHandle.innerHTML = "";	
			var addressSplit= addressHandle.value.split(" ").join("+")
			var xhr = new XMLHttpRequest();
           xhr.open('GET',"https://maps.googleapis.com/maps/api/geocode/json?address="+addressSplit+"&key=AIzaSyBZEUR89PrVcJnWmRCySjIePLjjmGr_VlQ");
           xhr.onreadystatechange = function(){
        		if(xhr.readyState == 4 && xhr.status == 200){
          			var response = JSON.parse(xhr.responseText);
          			console.log(response);
          			      result = response.results;

          			     var latitude = "";
          			     var langitude = "";
          				result.forEach(function(res){
          					 latitude = res.geometry.location.lat;
          					 langitude = res.geometry.location.lng;
          					console.log(latitude);
          					console.log(langitude);
          				});
          				latitudeHandle.value = latitude;
          				langitudeHandle.value = langitude;
          		}		
          	};			
           xhr.send();
		}
	};
</script>

app/views/rooms/confirmed_unconfirmed_bookings.html.erb
<h2>Listing confirmed and unconfirmed bookings</h2>
 <table class="table">
<thead>
	<tr>
	<th>RoomName</th>
	<th>Start_Date</th>
	<th>End_Date</th>
	<th>is_confirmed</th>
	<th>Amount</th>
	</tr>
</thead>
<tbody>
<% if @bookings.empty? %>
	<%= "Record not found" %>
	<% else %>
	<% @bookings.each do |booking| %>
	<tr>
		<td><%#= booking.room.name  %></td>
	  	<td><%= booking.start_date  %></td>
		<td><%= booking.end_date %></td>
		<td><%= booking.is_confirmed %></td>
		<% no_of_days_booked = (booking.start_date .. booking.end_date).to_a.count %>
		<td><%= booking.room.price * no_of_days_booked %></td>
		
		<%# if can? :update,Room.new %>
			<!-- <td><%#= form_for @booking do |f| %>
				<%#= f.label :is_confirmed %>
				<%#= f.hidden_field :booking ,value: true %></td>
				
				<td><%#= f.submit "submit" %></td></td>
			<%# end %> -->
		<%# end %>	

		</tr>
	<% end %>
<% end %>	
</tbody>
</table>

app/views/rooms/edit.html.erb
<div class="panel panel-info">
  <div class="panel-heading">Editing Room</div>
    <div class="panel-body">
		<%= render 'form' %>
	</div>
</div>	

app/views/rooms/index.html.erb
<h2>Listing Rooms(<%= @rooms.length %>)</h2>

<% if can? :myroom ,Room.new %> 
	<%= link_to "MyRoom",rooms_myroom_path %>	
<% end %>

<% if can? :unauthorized,Room.new %> 
	<%= link_to "UnAuthorize" ,rooms_unauthorized_path %> 
<% end %>

<% if can? :confirmed_unconfirmed_bookings,Room.new %>
	<%= link_to "Bookings",rooms_confirmed_unconfirmed_bookings_path %>
<% end %>

<table class="table">

<thead>
	<tr>
	<th>Name</th>
	<th>Description</th>
	<th>Address</th>
	<th>Price</th>
	<th>Langitude</th>
	<th>Langitude</th>
	<th>is_authorized</th>
	<th>City</th>
	<th>User</th>
	</tr>
</thead>
<tbody>
<% if @rooms.empty? %>
	<%= "Record not found" %>
	<% else %>
	<% @rooms.each do |room| %>
	<tr>
	  	<td><%= link_to room.name,room_path(room.id) %></td>
		<td><%= room.description %></td>
		<td><%= room.address %></td>
		<td><%= room.price %></td>
		<td><%= room.langitude %></td>
		<td><%= room.langitude %></td>
		<td><%= room.is_authorized %></td>
		<td><%= room.city.name %></td>
		<td><%= room.user.username %></td>
		</tr>
	<% end %>
<% end %>	
</tbody>
</table>

<%= link_to "Add Room",new_room_path %>

app/views/rooms/myroom.html.erb
<h2>My Rooms</h2>
<table class="table">

<thead>
	<tr>
	<th>Name</th>
	<th>Description</th>
	<th>Address</th>
	<th>Price</th>
	<th>Langitude</th>
	<th>Langitude</th>
	<th>is_authorized</th>
	<th>City</th>
	<th>User</th>
	</tr>
</thead>
<tbody>
<% if @myroom_array.empty? %>
	<%= "Record not found" %>
	<% else %>
	<% @myroom_array.each do |room| %>
	<tr>
	  	<td><%= room.name  %></td>
		<td><%= room.description %></td>
		<td><%= room.address %></td>
		<td><%= room.price %></td>
		<td><%= room.langitude %></td>
		<td><%= room.langitude %></td>
		<td><%= room.is_authorized %></td>
		<td><%= room.city.name %></td>
		<td><%= room.user.username %></td>
		<td><%= link_to "Edit",edit_room_path(room.id) %></td>
		</tr>
	<% end %>
<% end %>	
</tbody>
</table>

app/views/rooms/new.html.erb
<div class="panel panel-info">
  <div class="panel-heading">Add New Room</div>
    <div class="panel-body">
		<%= render 'form' %>
	</div>
</div>		

app/views/rooms/show.html.erb
<h2>Specific Room Details </h2>

Name: <%= @room.name %> <br/>
Description:<%= @room.description %><br/>
Address:<%= @room.address %><br/>
Price:<%= @room.price %><br/>
Latitude:<%= @room.latitude %><br/>
Langitude:<%= @room.langitude %><br/>
City:<%= @room.city.name %><br/>
User:<%= @room.user.username %><br/>
Amenity: <% @room.amenities.each do |amenity| %>
			<%= amenity.name %> 
         <% end %>  <br/>
Image:<% @room.images.each do |image| %>
          <%= image_tag image.image.url %>
       <% end %>

<!-- Displaying map -->
<iframe
  width="600"
  height="450" 
   frameborder="0" style="border:0" 
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBZEUR89PrVcJnWmRCySjIePLjjmGr_VlQ&q=<%= @room.address %>,<%= @room.latitude %>,<%= @room.langitude %>"allowfullscreen> 
</iframe>
<br/>

<%= link_to "edit", edit_room_path(@room.id)%> |
<%= link_to "destroy", room_path(@room.id), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>
<br/>
<br/>
<br/>

<div>
<%= form_for @booking do |f| %>
	<%= f.label :start_date %>
	<%= f.date_field :start_date %><br/>
	<%= f.label :end_date %>
	<%= f.date_field :end_date %><br/>
	<%= f.label :is_confirmed %>
	<%= f.check_box :is_confirmed %><br/>
	
	<%= f.hidden_field :room_id, value: @room.id %>
	<%= f.submit %>
<% end %>
</div>

app/views/rooms/unauthorized.html.erb
<h2>Listing Unauthorized Rooms</h2>
 <table class="table">
<thead>
	<tr>
	<th>Name</th>
	<th>Description</th>
	<th>Address</th>
	<th>Price</th>
	<th>Langitude</th>
	<th>Langitude</th>
	<th>is_authorized</th>
	<th>City</th>
	<th>User</th>
	</tr>
</thead>
<tbody>
<% if @rooms.empty? %>
	<%= "Record not found" %>
	<% else %>
	<% @rooms.each do |room| %>
	<tr>
	  	<td><%= room.name  %></td>
		<td><%= room.description %></td>
		<td><%= room.address %></td>
		<td><%= room.price %></td>
		<td><%= room.langitude %></td>
		<td><%= room.langitude %></td>
		<td><%= room.is_authorized %></td>
		<td><%= room.city.name %></td>
		<td><%= room.user.username %></td>
		<%# if can? :update,Room.new %>
			<td><%= form_for @room do |f| %>
				<%= f.label :authorize %>
				<%= f.hidden_field :is_authorized ,value: true %></td>
				
				<td><%= f.submit "submit" %></td></td>
			<% end %>
		<%# end %>	

		</tr>
	<% end %>
<% end %>	
</tbody>
</table>