config/routes.rb
Rails.application.routes.draw do

  get 'form_validation/mobile'
  get 'form_validation/email'
  get 'form_validation/username'
  get 'rooms/unauthorized'
  get 'rooms/myroom'
  get 'rooms/confirmed_unconfirmed_bookings'

  devise_for :users
    scope "/admin" do
      resources :users
    end
  resources :amenities
  resources :cities
  resources :roles
  resources :rooms
  resources :images
  resources :bookings
  

  root to: "rooms#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentARoom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>
</head>
<body>
	<% if can? :read,Amenity.new %>
	 <%= link_to "Amenity",amenities_path %> |
	<% end %> 

	<% if can? :read,City.new %>
	 <%= link_to "city",cities_path %> |
	<% end %>

	 <% if can? :read,Role.new %>
	 	<%= link_to "Role",roles_path %>|
	 <% end %>

	 <% if can? :read,Room.new %>
	 	<%= link_to "Room",rooms_path %>|
	 <% end %>

	<% if can? :read,Image.new %>
	 	<%= link_to "Image",images_path %>|
	 <% end %>

	 <% if can? :read,Booking.new %>
	 	<%= link_to "Booking",bookings_path %>
	 <% end %>
	 <br/>

<% if user_signed_in? %>
	Welcome <%= current_user.username %>
	 <%= link_to "AccountSettings",edit_user_registration_path %> |
	 <%= link_to "Logout",destroy_user_session_path, method: :delete %> |
	<% else %>
	<%= link_to "Login", new_user_session_path %> | <%= link_to "Register", new_user_registration_path %>
<% end %>


<%= notice %>


<%= yield %>

</body>
</html>